# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e98b311802572e461539ec750384c02228c41f9cb635c171e4f74db5705b43d918cf90e0ad0ea3bef753715f06d4e67bb138254ff8985efa5b47deb6e228908

test:
  secret_key_base: 49700d8c74f6dc08515e91e420a08e4c80050fdb2e333ec4d5b94aae6cf54397a41ae85ba593f59245b294e86648666a2968880b82f7ee199e7d7db052d0ffcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
